### PR TITLE
 Added new features

### PR DESCRIPTION
**Pull request by ZainabR11**
### Summary
This pull request introduces the following improvements:
- Added a neon button for enhanced user interaction.
- Updated the text area component.
- Implemented new features and added a subtle animation effect to the heading.

### Why It's Valuable
These changes enhance the project visually and functionally, making it more engaging and user-friendly.

Issue number: add any feature you want #1

"Hacktoberfest-Aceepted"

### Demo Video
[Screen Recording - Made with RecordCast (1).webm](https://github.com/NisooJadhav/BionicReader/assets/122125525/c8befac0-4e56-4abf-91d4-ee81e29d1824)

### CODE REVIEW

**Comment by ZainabR11** [comment]
@NisooJadhav I hope you like it. Thank-you for your consideration.

**Comment by ZainabR11** [comment]
@NisooJadhav If you like it  then kindly accept the PR and use "Hacktoberfest-Accepted" label.

**Comment by NisooJadhav** [comment]
@ZainabR11 I said I wanted the half-bolded words in the below para, but I would do it no worries. Check over hacktoberfest.com if this PR counted there

**Comment by ZainabR11** [comment]
My apologies for the oversight, but I'm pleased to inform you that this pull request has been counted for Hacktoberfest. It's been a great experience contributing to your repository, and I'm thankful for the opportunity. @NisooJadhav

**Pull request merged**
